'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,Plus,SlidersHorizontal,Sparkles,Info,Save} from 'lucide-react';
import MeasurePicker from './MeasurePicker';
import NumberInput from './NumberInput';
import CostPlanner from './CostPlanner';
import Field,{ValidationContext,focusField,nativeErrors} from './FormField';
import RateSummary from './RateSummary';
import {Button} from './ui/button';
import {downloadFile} from '@/lib/exports';
import {money,type Project,type Replacement} from '@/lib/types';

const titles=['Building details','Budget & bills','Your upgrades'];
type Props={project:Project;onChange:(p:Project)=>void;onAnalyse:()=>void;loading:boolean;onDemo:()=>void;onReset:()=>void;onNotify:(message:string)=>void;serverErrors:Record<string,string>;connected:boolean};
const features=['solar','insulation','glazing','hvac','hot_water','lighting','rainwater','fixtures','durable'];
export default function GuidedForm({project:p,onChange,onAnalyse,loading,onDemo,onReset,onNotify,serverErrors,connected}:Props){
 const [step,setStep]=useState(0),[errors,setErrors]=useState<Record<string,string>>({}),[period,setPeriod]=useState<'annual'|'monthly'>('annual');
 const [zeroConfirmed,setZeroConfirmed]=useState(false),[terminalOpen,setTerminalOpen]=useState(!p.terminal_confirmed);
 const [review,setReview]=useState(false);const formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(!Object.keys(serverErrors).length)return;setErrors(serverErrors);const key=Object.keys(serverErrors)[0];setStep(['postcode','area','floors','rooms','bathrooms','occupants'].includes(key)?0:['zone','energy_kwh','water_kl','conventional_cost','cost_per_m2','tariff_note','price_date'].includes(key)||key.startsWith('materials')?1:2);setReview(false);requestAnimationFrame(()=>focusField(key));},[serverErrors]);
 const clear=(key:string)=>setErrors(old=>{if(!old[key])return old;const next={...old};delete next[key];return next;});
 const update=(values:Partial<Project>)=>{const rateKeys=['price_date','building_type','zone','tariff_mode','electricity_rate','electricity_daily','water_rate','water_fixed_annual','water_connected','wastewater_connected','stormwater','drought_tariff'];onChange({...p,...values,...(Object.keys(values).some(k=>rateKeys.includes(k))?{rates_snapshot:null}:{})});};
 function numeric(key:keyof Project,label:string,unit='',hint='',percent=false){const v=p[key];return <Field fieldKey={String(key)} label={label} hint={hint} help={hint||helpFor(String(key))} required={!['maintenance_annual','sustainable_cost'].includes(String(key))}><div className="input-unit"><NumberInput aria-label={label} min={percent&&key.endsWith('escalation')?-20:['floors','occupants'].includes(String(key))?1:0} max={percent?key.endsWith('escalation')?30:100:undefined} step={['floors','rooms','bathrooms','occupants'].includes(key)?1:'any'} value={v==null?null:percent?Number((Number(v)*100).toFixed(4)):Number(v)} onValueChange={n=>update({[key]:n===null?null:n/(percent?100:1)})}/><span>{unit}</span></div></Field>;}
 function text(key:keyof Project,label:string,hint=''){return <Field fieldKey={String(key)} label={label} hint={hint} help={hint||helpFor(String(key))} required={key==='tariff_note'}><input aria-label={label} value={String(p[key]??'')} onChange={e=>update({[key]:e.target.value})}/></Field>;}
 function select(key:keyof Project,label:string,values:string[],labels?:string[]){return <Field fieldKey={String(key)} label={label} help={helpFor(String(key))} required><select aria-label={label} value={String(p[key])} onChange={e=>update({[key]:e.target.value,...(key==='building_type'&&e.target.value==='Commercial / Other'?{tariff_mode:'user'}:{})})}>{values.map((v,i)=><option key={v} value={v}>{labels?.[i]??v}</option>)}</select></Field>;}
 function check(key:keyof Project,label:string){return <Field fieldKey={String(key)} label={label} required={key==='terminal_confirmed'} help={key==='terminal_confirmed'?'These costs occur at the end of each study period. Zero is allowed when you deliberately confirm it.':undefined}><input type="checkbox" checked={Boolean(p[key])} onChange={e=>update({[key]:e.target.checked})}/></Field>;}
 function collect(n:number){const found:Record<string,string>={};
  if(n===0){if(!/^2\d{3}$/.test(p.postcode))found.postcode='Enter a four-digit Sydney postcode.';if(!(p.area>0))found.area='Enter your total floor area.';if(!Number.isInteger(p.floors)||p.floors<1)found.floors='Enter at least one whole floor.';if(!Number.isInteger(p.occupants)||p.occupants<1)found.occupants='Enter at least one occupant.';for(const key of ['rooms','bathrooms'] as const)if(!Number.isInteger(p[key])||p[key]<0)found[key]='Enter a whole number, including zero if applicable.';}
  if(n===1){if(!p.zone)found.zone='Choose the distributor shown on your electricity bill.';if(p.cost_mode==='detailed'&&!p.detailed_complete)found.detailed_complete='Confirm you included the full construction scope.';if(p.cost_mode==='detailed'&&!p.materials.length)found.detailed_complete='Add at least one cost item.';p.materials.forEach((m,i)=>{for(const key of ['quantity','unit_cost','maintenance'] as const)if(m[key]==null||!Number.isFinite(m[key])||m[key]<0)found['materials.'+i+'.'+key]='Enter a value, including zero if applicable.';});for(const key of ['energy_kwh','water_kl'] as const)if(p[key]==null||!Number.isFinite(p[key])||p[key]<0)found[key]='Enter annual use, or choose the labelled practice values.';if((p.energy_kwh===0||p.water_kl===0)&&!zeroConfirmed)found.zero_confirm='Confirm zero consumption is intentional.';if(p.tariff_mode==='user'){for(const key of ['electricity_rate','electricity_daily','water_rate','water_fixed_annual'] as const)if(p[key]==null)found[key]='Enter the rate from your bill.';if(!p.tariff_note.trim())found.tariff_note='Add a bill or contract reference.';}}
  if(n===2){if(!p.terminal_confirmed)found.terminal_confirmed='Confirm that you reviewed disposal and salvage.';if(p.mode==='literature'){for(const key of ['premium','energy_reduction','water_reduction','maintenance_reduction'] as const)if(p[key]==null)found[key]='Enter a percentage, including zero if applicable.';}}
  return found;
 }
 function present(found:Record<string,string>){setErrors(found);const first=Object.keys(found)[0];if(first)requestAnimationFrame(()=>focusField(first));return !first;}
 function next(){const found={...collect(step),...(formRef.current?nativeErrors(formRef.current):{})};if(present(found)){setStep(step+1);setReview(false);}}
 function submit(){for(let i=0;i<3;i++){const found=collect(i);if(Object.keys(found).length){setStep(i);setReview(false);present(found);return;}}const found=formRef.current?nativeErrors(formRef.current):{};if(!present(found))return;if(!review){setReview(true);requestAnimationFrame(()=>formRef.current?.querySelector<HTMLElement>('.review-heading')?.focus());}else onAnalyse();}
 const area=p.area*(p.area_unit==='ft²'?.092903:1),capital=p.cost_mode==='detailed'?p.materials.reduce((s,m)=>s+m.quantity*m.unit_cost,0)+p.other_construction:p.conventional_cost??(p.cost_per_m2??0)*area;
 function consumption(key:'energy_kwh'|'water_kl',label:string,unit:string){return <Field fieldKey={key} label={label} required help="Usage lets us calculate running costs and the benefit of upgrades. Enter consumption, not the amount paid." hint={key==='energy_kwh'?'Grid imports from your electricity bill—not dollars.':'Mains water from your water bill—not dollars.'}><div className="input-unit"><NumberInput min={0} value={p[key]==null?null:p[key]/(period==='monthly'?12:1)} placeholder="Enter consumption" onValueChange={v=>{setZeroConfirmed(false);update({[key]:v==null?null:v*(period==='monthly'?12:1)});}}/><span>{unit}/{period==='monthly'?'month':'year'}</span></div>{period==='monthly'&&p[key]!=null&&<small>Annual equivalent: {p[key].toLocaleString('en-AU',{maximumFractionDigits:2})} {unit}</small>}</Field>;}
 return <ValidationContext.Provider value={{errors,clear}}><div className="project-card"><div className="form-topline"><span><span className="live-dot"/> SYDNEY PROJECT</span><div><button type="button" disabled={loading} onClick={()=>{onDemo();setStep(0);setErrors({});setZeroConfirmed(false);}}>Try an example</button><button type="button" disabled={loading} onClick={()=>{onReset();setStep(0);setErrors({});setZeroConfirmed(false);}}>Start fresh</button></div></div>
 <div className="form-stepper">{titles.map((title,i)=><button type="button" key={title} aria-current={step===i?'step':undefined} className={step===i?'active':i<step?'complete':''} disabled={loading} onClick={()=>{if(i<=step){setStep(i);setErrors({});}else next();}}><span>{i<step?<Check size={13}/>:i+1}</span><b>{title}</b></button>)}</div>
 {p.preset==='legacy_6star'&&<div className="sample-note">Historical study inputs loaded. <button type="button" onClick={()=>update({preset:'code_minimum_7star',mode:'itemised',sustainable_cost:null,budget_range:null})}>Switch to a new project</button></div>}
 <form ref={formRef} onSubmit={e=>{e.preventDefault();if(step<2)next();else submit();}} noValidate><fieldset disabled={loading}>
 <div className="form-heading"><span className="eyebrow">STEP {step+1} OF 3</span><h3>{review&&step===2?'Review your comparison.':['Tell us about your building.','A budget. Two bills.','Choose what you’d improve.'][step]}</h3><p>{['Start with your Sydney location and building size.','Enter what you know. Keep estimates clearly labelled.','Compare individual upgrades, then review your assumptions.'][step]}</p></div>
 {p.input_quality==='demo'&&<div className="sample-note"><Info size={15}/>Example project—replace these values with your own.</div>}<p className="required-legend"><span>*</span> Required · Select ⓘ for help</p>{Object.keys(errors).length>0&&<p className="validation-announcement" role="status">Check the highlighted fields below.</p>}
 {step===0&&<><section className="form-block"><h4>Project & location</h4><div className="field-grid">{text('name','Project name (optional)','A name you’ll recognise later.')}<Field fieldKey="postcode" required help="Your postcode identifies the Sydney project location. Confirm service coverage using your bills." label="Sydney postcode" hint="Sydney only. Confirm your distributor and Sydney Water coverage from your bills."><input inputMode="numeric" pattern="2[0-9]{3}" maxLength={4} placeholder="e.g. 2000" value={p.postcode} onChange={e=>update({postcode:e.target.value.replace(/\D/g,'')})}/></Field>{select('building_type','Building type',['Residential House','Apartment','Commercial / Other'])}</div></section><section className="form-block"><h4>Building size & people</h4><div className="field-grid"><Field fieldKey="area" required help="The combined area of every floor helps estimate building quantities and compare upgrades." label="Total floor area" hint="Include all floors."><div className="area-control"><NumberInput min={1} value={p.area} onValueChange={v=>update({area:v as number})}/><select aria-label="Floor area unit" value={p.area_unit} onChange={e=>update({area_unit:e.target.value})}><option>m²</option><option>ft²</option></select></div></Field>{numeric('floors','Number of floors')}{numeric('occupants','Number of occupants')}</div></section><details className="form-details"><summary>Optional building details <Plus size={14}/></summary><div className="field-grid">{numeric('rooms','Bedrooms / rooms')}{numeric('bathrooms','Bathrooms')}{select('quality','Build quality',['Standard','Mid-range','Premium'])}{select('input_quality','Input quality',['estimate','actual','demo'],['Estimates','Quotes & measured use','Example assumptions'])}</div></details></>}
 {step===1&&<><CostPlanner project={p} onChange={onChange}/><section className="form-block"><div className="block-heading"><span className="block-number">02</span><div><h4>How much electricity & water?</h4><p>Consumption, rather than the amount you pay.</p></div></div><div className="choice-row">{(['annual','monthly'] as const).map(v=><button key={v} type="button" className={period===v?'selected':''} aria-pressed={period===v} onClick={()=>setPeriod(v)}>{v==='annual'?'Annual use':'Monthly average'}</button>)}</div><div className="field-grid">{consumption('energy_kwh','Electricity consumption','kWh')}{consumption('water_kl','Water consumption','kL')}</div><details className="form-details"><summary>No bills yet? Use an illustrative estimate</summary><p className="small-note">Practice values of 5,200 kWh and 200 kL annually are not estimates of your house. For a new building, replace them with a documented design estimate.</p><button type="button" className="text-link" onClick={()=>{update({energy_kwh:5200,water_kl:200,input_quality:'demo'});setZeroConfirmed(false);}}>Use practice consumption values</button></details>{(p.energy_kwh===0||p.water_kl===0)&&<div className="zero-warning"><Info size={16}/><div><b>Zero use means no usage savings.</b><p>Related upgrades still cost money. Fixed connection charges remain payable.</p><Field fieldKey="zero_confirm" label="Confirm zero consumption" required><input type="checkbox" checked={zeroConfirmed} onChange={e=>setZeroConfirmed(e.target.checked)}/><span>These zero values are intentional.</span></Field></div></div>}</section>
 <section className="form-block"><div className="block-heading"><span className="block-number">03</span><div><h4>Which utility rates should we use?</h4><p>Reference rates or the prices on your own bills.</p></div></div>{select('zone','Electricity distributor',['','Ausgrid','Endeavour Energy','Essential Energy'],['Choose your distributor','Ausgrid','Endeavour Energy','Essential Energy'])}<details className="form-details"><summary>Where do I find my distributor?</summary><p className="small-note">Look for “distributor” or “network” on your electricity bill. It can differ from your electricity retailer. Postcode alone is not used to guess it.</p></details><div className="choice-row"><button type="button" disabled={p.building_type==='Commercial / Other'} className={p.tariff_mode==='official'?'selected':''} aria-pressed={p.tariff_mode==='official'} onClick={()=>update({tariff_mode:'official'})}>Sydney reference rates</button><button type="button" className={p.tariff_mode==='user'?'selected':''} aria-pressed={p.tariff_mode==='user'} onClick={()=>update({tariff_mode:'user'})}>My bill rates</button></div>
 {p.tariff_mode==='user'?<><p className="small-note">Enter tax-inclusive rates from your residential bill or commercial contract.</p><div className="field-grid">{numeric('electricity_rate','Electricity usage rate','AUD/kWh')}{numeric('electricity_daily','Daily electricity supply','AUD/day')}{numeric('water_rate','Water usage rate','AUD/kL')}{numeric('water_fixed_annual','Combined fixed water charges','AUD/year')}{text('tariff_note','Bill / contract reference')}<Field fieldKey="price_date" required label="Bill date" help="The date records which price period your rates represent."><input type="date" value={p.price_date} onChange={e=>update({price_date:e.target.value})}/></Field></div></>:<div className="rate-summary"><RateSummary project={p}/><p>Dated 2026–27 reference rates. Electricity depends on your chosen distributor. These are reference charges, not a retailer quote.</p><a href="/methodology">View rates & sources →</a><details><summary>Review connections & rate date</summary><div className="check-group">{check('water_connected','Metered Sydney Water supply')}{check('wastewater_connected','Wastewater connection')}{check('stormwater','Stormwater charge applies')}{check('drought_tariff','Drought water rate applies')}</div><Field fieldKey="price_date" required label="Price reference date" help="Reference tariffs must be valid for the selected date."><input type="date" value={p.price_date} onChange={e=>update({price_date:e.target.value})}/></Field></details></div>}</section></>}
 {step===2&&!review&&<><div className="choice-row"><button type="button" className={p.mode==='itemised'?'selected':''} aria-pressed={p.mode==='itemised'} onClick={()=>update({mode:'itemised',preset:'code_minimum_7star',sustainable_cost:null})}>Choose upgrades</button><button type="button" className={p.mode==='literature'?'selected':''} aria-pressed={p.mode==='literature'} onClick={()=>update({mode:'literature',preset:'code_minimum_7star'})}>Research scenarios</button></div><p className="small-note">Compare upgrades beyond your baseline specification. This is an indicative comparison, not a BASIX or NatHERS assessment.</p>{p.mode==='itemised'?<MeasurePicker project={p} onChange={onChange}/>:<><div className="package-grid">{features.map(id=><button type="button" key={id} className={p.features.includes(id)?'chosen':''} aria-pressed={p.features.includes(id)} onClick={()=>{const fs=p.features.includes(id)?p.features.filter(f=>f!==id):[...p.features,id];update({features:fs,...(!fs.some(f=>['solar','insulation','glazing','hvac','hot_water','lighting'].includes(f))?{energy_reduction:0}:{}),...(!fs.some(f=>['rainwater','fixtures'].includes(f))?{water_reduction:0}:{}),...(!fs.includes('durable')?{maintenance_reduction:0}:{})});}}>{id.replaceAll('_',' ')}{p.features.includes(id)&&<Check size={13}/>}</button>)}</div><div className="field-grid">{numeric('sustainable_cost','Sustainable construction quote','AUD','Optional; overrides the percentage premium.')}{numeric('premium','Estimated construction premium','%','Used when no sustainable quote is supplied.',true)}{numeric('energy_reduction','Electricity & gas reduction','%','Combined package assumption.',true)}{numeric('water_reduction','Mains water reduction','%','Fixed charges remain payable.',true)}{numeric('maintenance_reduction','Maintenance reduction','%','One adjustment for the whole package.',true)}</div><p className="estimated-capital">Estimated sustainable construction <b>{money(p.sustainable_cost??capital*(1+p.premium))}</b></p>{select('performance_source','Performance basis',['research','user'],['Literature assumptions','Project estimate / simulation'])}</>}
 <div className="horizon-picker"><span>Main study period</span><div className="choice-row">{[30,40,50].map(y=><button type="button" key={y} className={p.years===y?'selected':''} aria-pressed={p.years===y} onClick={()=>update({years:y})}>{y} years</button>)}</div></div>
 <details className="form-details"><summary><span><SlidersHorizontal size={15}/> Financial assumptions & replacements</span></summary><div className="field-grid">{numeric('discount','Discount rate','%','Nominal rate.',true)}{numeric('energy_escalation','Electricity price growth','%/year','',true)}{numeric('water_escalation','Water price growth','%/year','',true)}{numeric('maintenance_escalation','Maintenance price growth','%/year','',true)}{numeric('other_escalation','Other cost growth','%/year','',true)}{numeric('terminal_escalation','End-of-life price growth','%/year','',true)}{numeric('maintenance_annual','Annual building maintenance','AUD','Optional; overrides the percentage.')}{numeric('maintenance_fraction','Maintenance share of capital','%/year','Review this assumption.',true)}{numeric('other_annual','Other annual expense','AUD')}</div>{p.replacements.map((r,i)=><div className="field-grid" key={i}>{(['name','scenario','interval','cost','escalation'] as const).map(key=><Field key={key} fieldKey={`replacements.${i}.${key}`} required label={{name:"Replacement name",scenario:"Applies to",interval:"Replacement interval (years)",cost:"Replacement cost (AUD)",escalation:"Replacement price growth (%/year)"}[key]} help="Include the same construction scope in both scenarios. Replacement costs occur at this interval.">{key==='name'?<input value={r.name} onChange={e=>update({replacements:p.replacements.map((v,n)=>n===i?{...v,name:e.target.value}:v)})}/>:key==='scenario'?<select value={r.scenario} onChange={e=>update({replacements:p.replacements.map((v,n)=>n===i?{...v,scenario:e.target.value as Replacement['scenario']}:v)})}>{['both','conventional','sustainable'].map(v=><option key={v}>{v}</option>)}</select>:<NumberInput min={key==='interval'?1:key==='escalation'?-20:0} max={key==='interval'?100:key==='escalation'?30:undefined} step={key==='interval'?1:'any'} value={r[key]==null?null:key==='escalation'?Number((r[key]*100).toFixed(4)):r[key]} onValueChange={v=>update({replacements:p.replacements.map((row,n)=>n===i?{...row,[key]:v==null?null:key==='escalation'?v/100:v}:row)})}/>}</Field>)}<button type="button" className="text-link" onClick={()=>update({replacements:p.replacements.filter((_,n)=>n!==i)})}>Remove replacement</button></div>)}<button type="button" className="text-link" onClick={()=>update({replacements:[...p.replacements,{name:'Component',scenario:'both',interval:15,cost:0,escalation:.025}]})}>Add replacement</button></details>
 <details className="form-details"><summary>Gas use & solar export credit</summary><div className="field-grid">{numeric('gas_mj','Annual gas','MJ/year')}{numeric('gas_rate','Gas usage rate','AUD/MJ')}{numeric('gas_daily','Daily gas supply','AUD/day')}{text('gas_note','Gas bill reference')}{numeric('feed_in_rate','Solar export credit','AUD/kWh')}</div></details>
 <details className="form-details terminal-review" open={terminalOpen} onToggle={e=>setTerminalOpen(e.currentTarget.open)}><summary>Disposal & salvage {p.terminal_confirmed?'— reviewed':'— review required'}</summary><p className="small-note">Base-year estimates of disposal costs and salvage credits. Zero is allowed when explicitly confirmed.</p><div className="field-grid">{numeric('disposal_conventional','Conventional disposal','AUD')}{numeric('disposal_sustainable','Sustainable disposal','AUD')}{numeric('residual_conventional','Conventional salvage','AUD')}{numeric('residual_sustainable','Sustainable salvage','AUD')}</div>{check('terminal_confirmed','I reviewed these values, including any zeros.')}</details>
 <label className="research-toggle"><input type="checkbox" checked={p.web_research} onChange={e=>update({web_research:e.target.checked})}/><span><b>Add web research</b><small>Optional Tavily context. Calculations work without it.</small></span></label><div className="input-summary"><h4>Ready to compare?</h4><p>{p.name||'Sydney project'} · {p.postcode} · {area?.toFixed(1)} m²</p><p>{money(capital)} construction · {p.energy_kwh?.toLocaleString('en-AU')} kWh/year · {p.water_kl?.toLocaleString('en-AU')} kL/year</p><p>{p.mode==='itemised'?`${p.selected_measures.length} selected upgrades`:'Research package'} · All three horizons calculated</p></div></>}
 {step===2&&review&&<section className="comparison-review"><h4 className="review-heading" tabIndex={-1}>Check before calculating</h4><p>Your estimates stay visible in the result. Edit any section before continuing.</p>{[{title:'Building',value:`${p.name||'Sydney project'} · ${p.postcode} · ${area.toFixed(1)} m² · ${p.floors} floor(s) · ${p.occupants} occupants`,step:0},{title:'Budget & bills',value:`${money(capital)}${p.budget_range?' midpoint ('+money(p.budget_range[0])+'–'+money(p.budget_range[1])+')':''} · ${p.energy_kwh.toLocaleString('en-AU')} kWh/year · ${p.water_kl.toLocaleString('en-AU')} kL/year · ${p.zone} · ${p.tariff_mode==='official'?'reference rates':'your bill rates'}`,step:1},{title:'Upgrades & assumptions',value:`${p.mode==='itemised'?p.selected_measures.length+' upgrades':'Research package'} · ${p.years} years · ${(p.discount*100).toFixed(1)}% discount · ${p.input_quality==='actual'?'Quotes & measured use':'Estimates / example inputs'}`,step:2}].map(item=><article key={item.title}><div><h5>{item.title}</h5><p>{item.value}</p></div><button className="text-link" type="button" onClick={()=>{setStep(item.step);setReview(false);setErrors({});}}>Edit {item.title.toLowerCase()}</button></article>)}<p className="small-note">A sustainable option can cost more. The calculation uses your assumptions without forcing savings.</p></section>}
 <div className="form-bottom"><div><button type="button" className="text-link" onClick={()=>{downloadFile(JSON.stringify({kind:'greencost-draft-v2',project:p},null,2),'GreenCost-draft.json');onNotify('Draft downloaded. Import it from My projects to resume.');}}><Save size={15}/>Save draft</button></div><div>{step>0&&<Button type="button" variant="ghost" onClick={()=>{if(review)setReview(false);else setStep(step-1);setErrors({});}}><ArrowLeft size={14}/>Back</Button>}<Button type="submit" disabled={loading||(step===2&&review&&!connected)}>{step===0?'Continue to budget':step===1?'Continue to upgrades':loading?'Analysing…':review?'Compare my building':'Review comparison'}{step<2?<ArrowRight size={16}/>:<Sparkles size={16}/>}</Button></div></div>
 </fieldset></form></div></ValidationContext.Provider>;
}

function helpFor(key:string){const explanations:Record<string,string>={name:'Use a recognisable project name. It is included in saved files and reports.',zone:'Your distributor owns the network. It can differ from your electricity retailer.',floors:'Count each storey. Floor area must include all storeys.',occupants:'People using the building help describe the scenario; bill consumption determines utility costs.',rooms:'Used to describe the building. Enter zero if there are no bedrooms.',bathrooms:'Used to estimate fittings and quantities.',discount:'A nominal discount rate converts future costs into present value.',premium:'The percentage added to your conventional budget in a research package.',energy_reduction:'Combined usage reduction for the research package. Fixed supply charges remain.',water_reduction:'Reduction in mains-water use. Fixed water charges remain.',maintenance_reduction:'One adjustment to maintenance for the full package.'};return explanations[key]??'Review this assumption using your bill, drawings or a comparable project quote. It affects the comparison.';}
