'use client';
import {useEffect,useState} from 'react';
import {Leaf,Sun,Droplets,Layers3,Check,Plus} from 'lucide-react';
import NumberInput from './NumberInput';
import QuotePair from './QuotePair';
import Field,{focusField} from './FormField';
import {api,ApiError,money,type Project,type MeasureCost,type Measure} from '@/lib/types';

type RoofDiagnostic={area:number;area_unit:string;area_m2:number;floors:number;roof_area_m2:number;max_solar_kw:number;solar_kw:number;roof_overridden:boolean};
export default function MeasurePicker({project:p,onChange,onEditBuilding}:{project:Project;onChange:(p:Project)=>void;onEditBuilding?:()=>void}){
 const [category,setCategory]=useState('comfort'),[otherEfficiency,setOtherEfficiency]=useState(false);
 const groups=[{id:'comfort',name:'Comfort & design',Icon:Leaf,ids:['insulation','glazing','airtightness_shading']},{id:'energy',name:'Clean energy',Icon:Sun,ids:['solar_pv','hot_water','hvac','lighting','smart_controls']},{id:'water',name:'Water saving',Icon:Droplets,ids:['rainwater','water_fixtures']},{id:'materials',name:'Building materials',Icon:Layers3,ids:['sustainable_materials']}];
 const [catalogue,setCatalogue]=useState<Measure[]>([]),[rows,setRows]=useState<MeasureCost[]>([]),[premium,setPremium]=useState(0),[error,setError]=useState('');
 const [roofIssue,setRoofIssue]=useState<RoofDiagnostic|null>(null),[inputError,setInputError]=useState(false);
 const [previewFor,setPreviewFor]=useState<Project|null>(null);const pending=previewFor!==p;
 const [maximum,setMaximum]=useState<number|null>(null),[retry,setRetry]=useState(0),[catalogueError,setCatalogueError]=useState(false);
 useEffect(()=>{let active=true;setCatalogueError(false);api<Measure[]>('/v1/measures').then(data=>{if(active)setCatalogue(data);}).catch(()=>{if(active)setCatalogueError(true);});return()=>{active=false;};},[retry]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{api<{measures:MeasureCost[];premium:number;takeoff:{quantities:{max_solar_kw:number}}}>('/v1/preview',p).then(r=>{if(active){setRows(r.measures);setPremium(r.premium);setMaximum(r.takeoff.quantities.max_solar_kw);setPreviewFor(p);setError('');setRoofIssue(null);setInputError(false);}}).catch(e=>{if(active){setPreviewFor(p);setRows([]);setError(e.message);setInputError(e instanceof ApiError&&e.status===422);const diagnostic=e instanceof ApiError&&e.details?.code==='solar_capacity'?e.details.geometry as RoofDiagnostic:null;setRoofIssue(diagnostic);setMaximum(diagnostic?.max_solar_kw??null);}});},250);return()=>{active=false;clearTimeout(timer);};},[p,retry]);
 function retryEstimate(){setPreviewFor(null);setError('');setRows([]);setRoofIssue(null);setMaximum(null);setRetry(v=>v+1);}
 function toggle(id:string){onChange({...p,selected_measures:p.selected_measures.includes(id)?p.selected_measures.filter(x=>x!==id):[...p.selected_measures,id]});}
 return <section className="measure-picker" aria-label="Individual upgrades" aria-busy={pending}><div className="estimated-capital"><span>Selected upgrade differences</span><b>{pending?'Calculating…':error?'Check inputs':money(premium)}</b></div><p className="small-note">Each price is the installed difference versus your baseline, including GST. Indicative prices need builder review. Already required measures receive zero cost and zero modelled benefit.</p>
 {catalogueError&&<p className="field-error" role="alert">The upgrade catalogue could not load. <button type="button" className="text-link" onClick={()=>setRetry(v=>v+1)}>Retry upgrades</button></p>}{!pending&&error&&<div className="estimate-error" role="alert"><b>{roofIssue?'Review your roof and solar size':inputError?'Review the estimate inputs':'The estimate could not load'}</b><p>{error}</p>{roofIssue&&<><dl className="roof-diagnostics"><div><dt>Stored total floor area</dt><dd>{roofIssue.area.toLocaleString('en-AU')} {roofIssue.area_unit}{roofIssue.area_unit==='ft²'?` (${roofIssue.area_m2.toLocaleString('en-AU',{maximumFractionDigits:2})} m²)`:''}</dd></div><div><dt>Number of floors</dt><dd>{roofIssue.floors}</dd></div><div><dt>{roofIssue.roof_overridden?'Your roof-area override':'Estimated roof area'}</dt><dd>{roofIssue.roof_area_m2.toLocaleString('en-AU',{maximumFractionDigits:2})} m²</dd></div><div><dt>Selected solar size / estimated limit</dt><dd>{roofIssue.solar_kw.toLocaleString('en-AU')} / {roofIssue.max_solar_kw.toLocaleString('en-AU',{maximumFractionDigits:2})} kW</dd></div></dl><p className="small-note">{roofIssue.roof_overridden?'A manual roof area is replacing the estimate from your building size.':'Roof area is estimated from total floor area divided by floors, with a roof-shape allowance.'} Only part of that roof is assumed suitable for panels. Changing the relevant input rechecks the estimate automatically.</p><div className="estimate-actions">{onEditBuilding&&<button type="button" className="text-link" onClick={onEditBuilding}>Review area, units & floors</button>}<button type="button" className="text-link" onClick={()=>focusField('solar_kw')}>Edit solar size</button><button type="button" className="text-link" onClick={()=>focusField('quantity_overrides.roof_area_m2')}>Edit measured roof area</button>{roofIssue.roof_overridden&&<button type="button" className="text-link" onClick={()=>{const q={...p.quantity_overrides};delete q.roof_area_m2;onChange({...p,quantity_overrides:q});}}>Use estimated roof area</button>}</div></>}{!roofIssue&&(inputError?<p className="small-note">Correct the relevant inputs to continue. The estimate rechecks automatically when an input changes.</p>:<button type="button" className="text-link" onClick={retryEstimate}>Retry estimate</button>)}</div>}
 <div className="baseline-check"><h4>What is already included?</h4><p className="small-note">An existing feature is not a new upgrade. Compare improvements against your actual specification.</p><Field fieldKey="hot_water" label="Baseline hot-water system" help="Heat-pump hot water is offered when replacing a less efficient system. If already included, do not count it as an additional upgrade."><select value={p.hot_water} onChange={e=>onChange({...p,hot_water:e.target.value,selected_measures:e.target.value==='Heat pump'?p.selected_measures.filter(id=>id!=='hot_water'):p.selected_measures})}>{['User specified','Electric resistance','Gas','Heat pump','Solar hot water'].map(v=><option key={v}>{v}</option>)}</select></Field></div>
 <div className="design-categories" role="group" aria-label="Sustainable feature categories">{groups.map(({id,name,Icon,ids})=><button type="button" key={id} aria-pressed={category===id} className={category===id?'selected':''} onClick={()=>setCategory(id)}><Icon size={22}/><b>{name}</b><small>{p.selected_measures.filter(v=>ids.includes(v)).length} selected</small></button>)}</div>
 <p className="small-note">{category==='comfort'?'Start with the building envelope. Improvements depend on glazing, shading, ventilation and the existing specification.':category==='energy'?'Solar and more efficient systems where they improve your baseline. Familiar products can still save energy; already-included features receive no additional benefit.':category==='water'?'Reduce mains-water demand using suitable fixtures and collection systems.':"Material choices can reduce environmental impact without reducing bills. Enter comparable installed quotes; no carbon saving is quantified here."}</p>
 {p.building_type==='Apartment Building'&&<p className="scope-note">Whole-building planning comparison. Review drawing quantities and installed project quotes. Current upgrade coefficients and capped solar/tank sizes are indicative; they do not model lifts, car parks, central plant or a complete high-rise specification. Include those costs and replacements in your project allowances.</p>}
 {p.building_type==='Apartment'&&<p className="scope-note">One apartment unit only. Shared rooftop solar, tanks and external-building work are excluded; check strata approval for other changes.</p>}
 {category==='energy'&&<button type="button" className="text-link" aria-expanded={otherEfficiency} onClick={()=>setOtherEfficiency(!otherEfficiency)}>{otherEfficiency?'Hide other efficiency options':'Explore other efficiency improvements'}</button>}
 <div className="measure-grid">{catalogue.filter(m=>groups.find(g=>g.id===category)!.ids.includes(m.id)).filter(m=>otherEfficiency||!['hvac','lighting','smart_controls'].includes(m.id)||p.selected_measures.includes(m.id)).filter(m=>p.building_type!=='Apartment'||!['solar_pv','rainwater','airtightness_shading'].includes(m.id)).filter(m=>m.id!=='hot_water'||['Electric resistance','Gas'].includes(p.hot_water)||p.selected_measures.includes(m.id)).map(m=>{const selected=p.selected_measures.includes(m.id),r=pending||error?undefined:rows.find(r=>r.id===m.id),required=p.code_required_measures.includes(m.id);return <article key={m.id} className={'measure-option '+(selected?'selected':'')}><button type="button" className="measure-choice" aria-pressed={selected} onClick={()=>toggle(m.id)}><span className="feature-icon">{selected?<Check size={22}/>:<Plus size={22}/>}</span><span><b>{m.name}</b><small>{m.plain_description}</small></span><span className="feature-action">{selected?'Added':'Add feature'}</span></button><span className="price-badge">{required?'Already included':r?.badge??'Indicative'}</span>{m.guidance_url&&<a className="feature-source" href={m.guidance_url} target="_blank" rel="noreferrer">Australian guidance ↗</a>}{selected&&<><p className="measure-price">{r?money(r.premium):pending?'Calculating…':'Check inputs'} <small>upgrade difference</small></p>{r&&<p className="small-note">{r.quantity.toFixed(1)} {r.quantity_driver.replaceAll('_',' ')} · {money(r.unit_price)} per unit<br/>Range {money(r.low)}–{money(r.high)}</p>}<details><summary>Price source & your quote</summary><p className="small-note">{r?.source??'Supplied package placeholder'} · {r?.price_date??'2026-10-05'}. Installed difference includes labour, margin and GST; they are not added twice. No automatic incentive is applied. Supply prices can be researched in your budget breakdown. These installed upgrade differences remain indicative unless you enter a comparable installed quote.</p><Field fieldKey={"price_overrides."+m.id} label="Your installed upgrade difference (AUD, GST included)" help="Optional. Leave blank to retain the indicative default."><input type="number" min="0" step="any" value={p.price_overrides[m.id]??''} placeholder="Use indicative default" onChange={e=>{const prices={...p.price_overrides};if(e.target.value==='')delete prices[m.id];else prices[m.id]=Number(e.target.value);onChange({...p,price_overrides:prices});}}/></Field><QuotePair id={m.id} project={p} onChange={onChange}/><label className="checkbox"><input type="checkbox" checked={required} onChange={()=>onChange({...p,code_required_measures:required?p.code_required_measures.filter(x=>x!==m.id):[...p.code_required_measures,m.id]})}/>Already included / required in my baseline</label></details></>}</article>;})}</div>
 <div className="selected-features"><h4>Your selected features · {p.selected_measures.length}</h4>{p.selected_measures.length?catalogue.filter(m=>p.selected_measures.includes(m.id)).map(m=><button type="button" key={m.id} onClick={()=>toggle(m.id)} aria-label={'Remove '+m.name}><Check size={14}/>{m.name}<span>Remove</span></button>):<p className="small-note">Choose features above. You can compare the baseline without any additions.</p>}</div>
 <details className="form-details"><summary>System sizes & drawing quantities</summary><div className="field-grid"><Field fieldKey="solar_kw" label="Solar array (kW)" required help="Used for solar cost, generation and roof-capacity checks."><NumberInput min={0} max={13.2} step={.1} value={p.quantity_overrides.solar_kw??p.solar_kw} onValueChange={v=>{const q={...p.quantity_overrides};delete q.solar_kw;onChange({...p,solar_kw:v as number,quantity_overrides:q});}}/><small>Indicative roof capacity: {maximum?.toFixed(2)??'…'} kW. Roof orientation and approval also matter.</small></Field><Field fieldKey="tank_kl" label="Rainwater tank (L)" required help="Used to estimate tank cost and stored rainwater."><NumberInput min={100} max={50000} step={100} value={p.tank_kl*1000} onValueChange={v=>onChange({...p,tank_kl:v==null?v as unknown as number:v/1000})}/></Field></div>
 <details className="form-details"><summary>Override estimated quantities</summary><p className="small-note">Use quantities from your drawings. Blank fields use the rectangular plan estimate.</p><div className="field-grid">{['perimeter_m','glazing_area_m2','roof_area_m2','net_wall_area_m2','ceiling_area_m2','catchment_area_m2'].map(key=><Field key={key} fieldKey={"quantity_overrides."+key} label={key.replaceAll('_',' ')} help="Optional drawing quantity. Leave blank to use the rectangular-plan estimate."><input type="number" min="0" step="any" value={p.quantity_overrides[key]??''} onChange={e=>{const q={...p.quantity_overrides};if(e.target.value==='')delete q[key];else q[key]=Number(e.target.value);onChange({...p,quantity_overrides:q});}}/></Field>)}</div></details></details></section>;
}
