'use client';
import {useEffect,useState} from 'react';
import NumberInput from './NumberInput';
import QuotePair from './QuotePair';
import Field from './FormField';
import {api,money,type Project,type MeasureCost,type Measure} from '@/lib/types';

export default function MeasurePicker({project:p,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const [catalogue,setCatalogue]=useState<Measure[]>([]),[rows,setRows]=useState<MeasureCost[]>([]),[premium,setPremium]=useState(0),[error,setError]=useState('');
 const [previewFor,setPreviewFor]=useState<Project|null>(null);const pending=previewFor!==p;
 const [maximum,setMaximum]=useState<number|null>(null),[retry,setRetry]=useState(0),[catalogueError,setCatalogueError]=useState(false);
 useEffect(()=>{let active=true;setCatalogueError(false);api<Measure[]>('/v1/measures').then(data=>{if(active)setCatalogue(data);}).catch(()=>{if(active)setCatalogueError(true);});return()=>{active=false;};},[retry]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{api<{measures:MeasureCost[];premium:number;takeoff:{quantities:{max_solar_kw:number}}}>('/v1/preview',p).then(r=>{if(active){setRows(r.measures);setPremium(r.premium);setMaximum(r.takeoff.quantities.max_solar_kw);setPreviewFor(p);setError('');}}).catch(e=>{if(active){setPreviewFor(p);setError(e.message);}});},250);return()=>{active=false;clearTimeout(timer);};},[p,retry]);
 function toggle(id:string){onChange({...p,selected_measures:p.selected_measures.includes(id)?p.selected_measures.filter(x=>x!==id):[...p.selected_measures,id]});}
 return <section className="measure-picker" aria-label="Individual upgrades"><div className="estimated-capital"><span>Selected upgrade differences</span><b>{pending?'Calculating…':error?'Check inputs':money(premium)}</b></div><p className="small-note">Each price is the installed difference versus your baseline, including GST. Indicative prices need builder review. Already required measures receive zero cost and zero modelled benefit.</p>
 {catalogueError&&<p className="field-error" role="alert">The upgrade catalogue could not load. <button type="button" className="text-link" onClick={()=>setRetry(v=>v+1)}>Retry upgrades</button></p>}{error&&<p className="field-error" role="alert">{error} <button type="button" className="text-link" onClick={()=>setRetry(v=>v+1)}>Retry estimate</button></p>}
 <div className="measure-grid">{catalogue.map(m=>{const selected=p.selected_measures.includes(m.id),r=pending?undefined:rows.find(r=>r.id===m.id),required=p.code_required_measures.includes(m.id);return <article key={m.id} className={'measure-option '+(selected?'selected':'')}><label className="measure-choice"><input type="checkbox" checked={selected} onChange={()=>toggle(m.id)}/><span><b>{m.name}</b><small>{m.plain_description}</small></span></label><span className="price-badge">{r?.badge??'Indicative'}</span>{selected&&<><p className="measure-price">{r?money(r.premium):'Calculating…'} <small>upgrade difference</small></p>{r&&<p className="small-note">{r.quantity.toFixed(1)} {r.quantity_driver.replaceAll('_',' ')} · {money(r.unit_price)} per unit<br/>Range {money(r.low)}–{money(r.high)}</p>}<details><summary>Price source & your quote</summary><p className="small-note">{r?.source??'Supplied package placeholder'} · {r?.price_date??'2026-10-05'}. Installed difference includes labour, margin and GST; they are not added twice. No automatic incentive is applied. Supply prices can be researched in your budget breakdown. These installed upgrade differences remain indicative unless you enter a comparable installed quote.</p><Field fieldKey={"price_overrides."+m.id} label="Your installed upgrade difference (AUD, GST included)" help="Optional. Leave blank to retain the indicative default."><input type="number" min="0" step="any" value={p.price_overrides[m.id]??''} placeholder="Use indicative default" onChange={e=>{const prices={...p.price_overrides};if(e.target.value==='')delete prices[m.id];else prices[m.id]=Number(e.target.value);onChange({...p,price_overrides:prices});}}/></Field><QuotePair id={m.id} project={p} onChange={onChange}/><label className="checkbox"><input type="checkbox" checked={required} onChange={()=>onChange({...p,code_required_measures:required?p.code_required_measures.filter(x=>x!==m.id):[...p.code_required_measures,m.id]})}/>Already included / required in my baseline</label></details></>}</article>;})}</div>
 <details className="form-details"><summary>System sizes & drawing quantities</summary><div className="field-grid"><Field fieldKey="solar_kw" label="Solar array (kW)" required help="Used for solar cost, generation and roof-capacity checks."><NumberInput min={0} max={13.2} step={.1} value={p.solar_kw} onValueChange={v=>onChange({...p,solar_kw:v as number})}/><small>Indicative roof capacity: {maximum?.toFixed(1)??'…'} kW. Roof orientation and approval also matter.</small></Field><Field fieldKey="tank_kl" label="Rainwater tank (kL)" required help="Used to estimate tank cost and stored rainwater."><NumberInput min={.1} max={50} step={.1} value={p.tank_kl} onValueChange={v=>onChange({...p,tank_kl:v as number})}/></Field></div>
 <details className="form-details"><summary>Override estimated quantities</summary><p className="small-note">Use quantities from your drawings. Blank fields use the rectangular plan estimate.</p><div className="field-grid">{['perimeter_m','glazing_area_m2','roof_area_m2','net_wall_area_m2','ceiling_area_m2','catchment_area_m2'].map(key=><Field key={key} fieldKey={"quantity_overrides."+key} label={key.replaceAll('_',' ')} help="Optional drawing quantity. Leave blank to use the rectangular-plan estimate."><input type="number" min="0" step="any" value={p.quantity_overrides[key]??''} onChange={e=>{const q={...p.quantity_overrides};if(e.target.value==='')delete q[key];else q[key]=Number(e.target.value);onChange({...p,quantity_overrides:q});}}/></Field>)}</div></details></details></section>;
}
