'use client';
import {BarChart,Bar,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid} from 'recharts';
import {money,type Analysis,type ExtendedAnalysis} from '@/lib/types';
export default function ResearchOutputs({data,years}:{data:Analysis&ExtendedAnalysis;years:number}){
 const r=data.periods[String(years)],contributions=data.measure_contributions?.[String(years)];
 return <section className="research-outputs"><div className="section-heading"><div><p className="eyebrow">UNDER THE STATED ASSUMPTIONS</p><h2>What drives this comparison?</h2></div><span className="chart-unit">{data.project.mode==='itemised'?'Itemised upgrade scenario':'Literature-parameter scenario'}</span></div>
 <p className="muted">The sustainable case has a modelled {Math.abs(r.savings_percent??0).toFixed(2)}% {r.savings_aud>=0?'lower':'higher'} whole-life cost. The literature’s 10–20% saving is a research claim, not a target or a prediction.</p>
 {data.literature_scenarios&&<div className="literature-grid">{Object.entries(data.literature_scenarios).map(([name,periods])=>{const p=periods[String(years)];return <article key={name}><span className="eyebrow">{name} savings scenario</span><h3>{money(p.savings_aud)}</h3><p>{p.savings_percent?.toFixed(2)}% signed saving · {p.break_even_year===null?'No break-even':`Break-even Year ${p.break_even_year}`}</p></article>;})}</div>}
 {data.price_sensitivity&&<div className="literature-grid">{Object.entries(data.price_sensitivity).map(([name,periods])=>{const p=periods[String(years)];return <article key={name}><span className="eyebrow">{name} indicative price</span><h3>{money(p.savings_aud)}</h3><p>{p.break_even_year===null?'No break-even':`Break-even Year ${p.break_even_year}`}</p></article>;})}</div>}
 <div className="table-scroll"><table className="data-table"><caption>Cost category contributions — present value in AUD</caption><thead><tr><th>Category</th><th>Conventional</th><th>Sustainable</th><th>Signed saving</th><th>Share of net saving</th></tr></thead><tbody>{Object.entries(r.component_savings).map(([k,v])=><tr key={k}><td>{k}</td><td>{money(r.conventional.components[k])}</td><td>{money(r.sustainable.components[k])}</td><td>{money(v)}</td><td>{Math.abs(r.savings_aud)>1e-9?(v/r.savings_aud*100).toFixed(1)+'%':'Not defined'}</td></tr>)}</tbody></table></div><p className="small-note">Negative shares and shares above 100% are possible because upfront premiums offset operating savings. When net savings are zero, shares are undefined.</p>
 {contributions&&contributions.length>0&&<><h3>Contribution from each upgrade</h3><p className="small-note">Measures are added in catalogue order. Marginal contributions include interactions. Check terminal differences separately.</p><div className="chart-large"><ResponsiveContainer width="100%" height="100%"><BarChart data={contributions} margin={{top:20,right:20,bottom:60,left:15}}><CartesianGrid vertical={false} stroke="#daddd2"/><XAxis dataKey="name" interval={0} angle={-20} textAnchor="end" tick={{fontSize:10}}/><YAxis tickFormatter={v=>money(v)}/><Tooltip formatter={v=>money(Number(v))}/><Bar name="Marginal saving" dataKey="marginal_savings" fill="#31533f" isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Measure</th><th>Standalone saving</th><th>Interaction adjustment</th><th>Marginal saving</th></tr></thead><tbody>{contributions.map(m=><tr key={m.id}><td>{m.name}</td><td>{money(m.standalone_savings)}</td><td>{money(m.interaction_adjustment)}</td><td>{money(m.marginal_savings)}</td></tr>)}</tbody></table></div></>}
 <p className="small-note">Assumption version {data.assumption_version} · price reference {data.price_snapshot_date}. Prices, energy splits and geometry are indicative until reviewed.</p></section>;
}
