'use client';

import {BookOpen,Globe2,Calculator,Sparkles,Check,Loader2,Upload,ArrowUpRight,Minus} from 'lucide-react';
import type {Health} from '@/lib/types';

export const milestones=['validate_input','retrieve_local_evidence','research_online','check_data','calculate_scenarios','calculate_lcc','sensitivity_analysis','generate_explanation'];
const tasks=[{title:'Read your knowledge base',description:'Find relevant passages in your PDFs.',icon:BookOpen,stage:1},{title:'Explore official sources',description:'Add current web context with Tavily.',icon:Globe2,stage:2},{title:'Compare every year',description:'Calculate costs and test assumptions.',icon:Calculator,stage:6},{title:'Make the numbers make sense',description:'Explain the trade-offs with Gemini.',icon:Sparkles,stage:7}];
type Props={health:Health|null;loading:boolean;completed:string[];message:string;failed:boolean;finished:boolean;webEnabled:boolean;onUpload:(file:File)=>void;uploading:boolean;uploadMessage:string};

export default function ResearchAgent({health,loading,completed,message,failed,finished,webEnabled,onUpload,uploading,uploadMessage}:Props){
 const done=completed.length?Math.max(...completed.map(s=>milestones.indexOf(s))):-1;
 return <aside className={'agent-card '+(loading?'working':'')} aria-label="Research assistant"><div className="agent-card-top"><span className="eyebrow">MEET YOUR RESEARCH COMPANION</span><span className="agent-availability"><i/>{loading?'Working':finished?'Complete':'Ready to help'}</span></div>
 <div className="agent-visual" aria-hidden="true"><div className="agent-orbit orbit-one"/><div className="agent-orbit orbit-two"/><div className="agent-face"><div className="agent-antenna"/><div className="agent-eyes"><i/><i/></div><div className="agent-smile"/></div><span className="agent-satellite"><Sparkles size={16}/></span></div>
 <h3>{failed?'Let’s check those inputs.':loading?'Connecting the dots.':finished?'A little clarity, delivered.':'A second opinion. Backed by evidence.'}</h3><p className="agent-intro">Your inputs, your research, and a clearer view of the years ahead.</p>
 <ol className="agent-tasks">{tasks.map((task,i)=>{const complete=done>=task.stage;const skipped=(i===1&&(!webEnabled||!health?.tavily_configured))||(i===3&&!health?.gemini_configured);const current=loading&&!complete&&!skipped&&(i===0||done>=tasks[i-1].stage);const description=i===1&&!webEnabled?'Web research is off for this project.':i===1&&!health?.tavily_configured?'Tavily is not connected; using local evidence.':i===3&&!health?.gemini_configured?'Gemini is not connected; using calculated explanations.':task.description;return <li key={task.title} className={complete&&!skipped?'done':current?'running':''}><span className="agent-task-icon">{complete?skipped?<Minus size={16}/>:<Check size={16}/>:current?<Loader2 size={16} className="spin"/>:<task.icon size={16}/>}</span><div><b>{task.title}</b><small>{description}</small></div><span className="task-number">0{i+1}</span></li>;})}</ol>
 <div className={'agent-status '+(failed?'failed':'')} role="status" aria-live="polite">{message||(health?.gemini_configured?'Gemini is connected. Your assistant is ready.':'You can explore now. Connect Gemini for an AI explanation.')}</div>
 <div className="knowledge-upload"><div><BookOpen size={16}/><span><b>Your research library</b><small>{health?.knowledge.documents??0} documents · {health?.knowledge.chunks??0} passages</small></span></div><label className={'upload-button '+(uploading||loading?'disabled':'')}><input type="file" accept="application/pdf,.pdf" disabled={uploading||loading} onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(file);e.target.value='';}}/><Upload size={14}/>{uploading?'Indexing PDF…':'Add a PDF'}<ArrowUpRight size={14}/></label><small>Text-based PDFs, up to 10 MB. Stored in your local library.</small>{uploadMessage&&<p role="status">{uploadMessage}</p>}</div>
 <div className="connection-pills"><span className={health?.gemini_configured?'connected':''}><i/>Gemini</span><span className={health?.rag_ready?'connected':''}><i/>Chroma</span><span className={health?.tavily_configured?'connected':''}><i/>Tavily</span></div>
 </aside>;
}
