'use client';
import {BarChart,Bar,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid,Cell,ReferenceLine} from 'recharts';
import {money,type Analysis,type ExtendedAnalysis} from '@/lib/types';
import {useTheme,chartPalette,compactMoney} from '@/lib/theme';
export default function ResearchOutputs({data,years}:{data:Analysis&ExtendedAnalysis;years:number}){
 const palette=chartPalette[useTheme()];
 const r=data.periods[String(years)],contributions=data.measure_contributions?.[String(years)];
 return <section className="research-outputs"><div className="section-heading"><div><p className="eyebrow">UNDER THE STATED ASSUMPTIONS</p><h2>What drives this comparison?</h2></div><span className="chart-unit">{data.project.mode==='itemised'?'Itemised upgrade scenario':'Literature-parameter scenario'}</span></div>
 <p className="muted">The sustainable case has a modelled {Math.abs(r.savings_percent??0).toFixed(2)}% {r.savings_aud>=0?'lower':'higher'} whole-life cost. The literature’s 10–20% saving is a research claim, not a target or a prediction.</p>
 {data.literature_scenarios&&<div className="literature-grid">{Object.entries(data.literature_scenarios).map(([name,periods])=>{const p=periods[String(years)];return <article key={name}><span className="eyebrow">{name} savings scenario</span><h3>{money(p.savings_aud)}</h3><p>{p.savings_percent?.toFixed(2)}% signed saving · {p.break_even_year===null?'No break-even':`Break-even Year ${p.break_even_year}`}</p></article>;})}</div>}
 {data.price_sensitivity&&<div className="literature-grid">{Object.entries(data.price_sensitivity).map(([name,periods])=>{const p=periods[String(years)];return <article key={name}><span className="eyebrow">{name} indicative price</span><h3>{money(p.savings_aud)}</h3><p>{p.break_even_year===null?'No break-even':`Break-even Year ${p.break_even_year}`}</p></article>;})}</div>}
 <div className="table-scroll"><table className="data-table"><caption>Cost category contributions — present value in AUD</caption><thead><tr><th>Category</th><th>Conventional</th><th>Sustainable</th><th>Signed saving</th><th>Share of net saving</th></tr></thead><tbody>{Object.entries(r.component_savings).map(([k,v])=><tr key={k}><td>{k}</td><td>{money(r.conventional.components[k])}</td><td>{money(r.sustainable.components[k])}</td><td>{money(v)}</td><td>{Math.abs(r.savings_aud)>1e-9?(v/r.savings_aud*100).toFixed(1)+'%':'Not defined'}</td></tr>)}</tbody></table></div><p className="small-note">Negative shares and shares above 100% are possible because upfront premiums offset operating savings. When net savings are zero, shares are undefined.</p>
 {contributions&&contributions.length>0&&<><h3>Contribution from each upgrade</h3><p className="small-note">Measures are added in catalogue order. Marginal contributions include interactions. Check terminal differences separately.</p><div className="chart-large contribution-chart" style={{height:Math.max(260,Math.min(650,contributions.length*48+60))}}><ResponsiveContainer width="100%" height="100%"><BarChart data={contributions} layout="vertical" margin={{top:15,right:20,bottom:10,left:0}}><CartesianGrid horizontal={false} stroke={palette.grid} strokeDasharray="3 4"/><XAxis type="number" tickFormatter={v=>compactMoney(Number(v))} tick={{fill:palette.text,fontSize:11}} tickLine={false} axisLine={false}/><YAxis type="category" dataKey="name" width={150} tick={{fill:palette.text,fontSize:11}} tickLine={false} axisLine={false} tickFormatter={v=>String(v).length>26?String(v).slice(0,25)+'…':String(v)}/><ReferenceLine x={0} stroke={palette.grid}/><Tooltip formatter={v=>money(Number(v))} contentStyle={{backgroundColor:palette.surface,border:'1px solid '+palette.grid,borderRadius:10,color:palette.foreground,fontSize:12}} labelStyle={{color:palette.foreground}} itemStyle={{color:palette.foreground}} cursor={{fill:palette.grid,fillOpacity:.25}}/><Bar name="Marginal saving" dataKey="marginal_savings" fill={palette.sustainable} isAnimationActive={false}>{contributions.map(m=><Cell key={m.id} fill={m.marginal_savings<0?palette.conventional:palette.sustainable}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Measure</th><th>Standalone saving</th><th>Interaction adjustment</th><th>Marginal saving</th></tr></thead><tbody>{contributions.map(m=><tr key={m.id}><td>{m.name}</td><td>{money(m.standalone_savings)}</td><td>{money(m.interaction_adjustment)}</td><td>{money(m.marginal_savings)}</td></tr>)}</tbody></table></div></>}
 <p className="small-note">Assumption version {data.assumption_version} · price reference {data.price_snapshot_date}. Prices, energy splits and geometry are indicative until reviewed.</p></section>;
}
