'use client';
import {BookOpen,Calculator,Check,Loader2,ShieldCheck} from 'lucide-react';
import {providerStatus,retryableProvider} from '@/lib/provider-status';
import type {Analysis,Health} from '@/lib/types';
export const milestones=['validate_input','retrieve_local_evidence','research_online','check_data','calculate_scenarios','calculate_lcc','sensitivity_analysis','generate_explanation'];
type Props={activeStage:string;liveProviders:{gemini?:string;groq?:string;openrouter?:string;tavily?:string};health:Health|null;loading:boolean;completed:string[];message:string;failed:boolean;finished:boolean;webEnabled:boolean;researchStatus?:Analysis['research_status'];onRetry?:()=>void};
export default function ResearchAgent({activeStage,liveProviders,health,loading,completed,message,failed,finished,webEnabled,researchStatus,onRetry}:Props){
 const status=(provider:'gemini'|'groq'|'openrouter'|'tavily')=>{
  const configured=!!health?.[`${provider}_configured` as keyof Health],live=liveProviders[provider];
  if(loading&&live)return providerStatus(live,configured);
  if(loading){if(!configured)return 'Key not configured';if(provider==='tavily')return !webEnabled?'Off for this comparison':activeStage==='research_online'?'Fetching from Tavily…':'Waiting for its stage';return activeStage==='generate_explanation'?'Trying OpenRouter → Groq → Gemini; outcome pending':'Waiting for explanation stage';}
  return researchStatus?.[provider]==='not_requested'?'Not needed / not called':providerStatus(researchStatus?.[provider],configured,provider!=='tavily'||webEnabled);
 };
 const names=['Check project inputs','Read local evidence','Research official sources','Validate utility rates','Prepare both designs','Calculate yearly costs','Test assumptions','Prepare explanation'];
 return <aside className={'agent-card guide-card '+(loading?'workflow-running':finished?'workflow-finished':'')} aria-label="Comparison guide"><span className="eyebrow">YOUR COMPARISON GUIDE</span><h3>A clear view of the years ahead.</h3><p className="agent-intro">Start with your building and budget. Add upgrades to see whether their benefits recover the extra cost.</p><ol className="guide-steps"><li><Calculator size={20}/><div><b>Costs calculated in Python</b><p>Construction, utilities, maintenance and end-of-life costs.</p></div></li><li><BookOpen size={20}/><div><b>Evidence you can inspect</b><p>Included research and dated Sydney utility references.</p></div></li><li><ShieldCheck size={20}/><div><b>Estimates stay visible</b><p>A published supply price is different from an installed project quote.</p></div></li></ol>
 {(loading||finished||failed)&&<section className="workflow-progress" aria-label="Calculation progress"><div className="agent-status" role="status" aria-live="polite">{loading?<Loader2 size={16} className="spin"/>:finished?<Check size={16}/>:null}<b>{loading?'Building your comparison':finished?'Comparison complete':'Comparison interrupted'}</b><small>{completed.length} of {milestones.length} stages complete</small></div><div className="stage-progress-bar" role="progressbar" aria-label="Completed calculation stages" aria-valuemin={0} aria-valuemax={milestones.length} aria-valuenow={completed.length}><span style={{width:(completed.length/milestones.length*100)+'%'}}/></div><ol className="stage-timeline">{milestones.map((id,i)=>{const done=completed.includes(id),running=loading&&!done&&activeStage===id;return <li key={id} className={done?'complete':running?'running':''}><span>{done?<Check size={13}/>:running?<Loader2 size={13} className="spin"/>:i+1}</span><div><b>{names[i]}</b><small>{done?'Complete':running?'Running…':failed?'Not completed':'Waiting'}</small></div></li>;})}</ol><p className="small-note">{message}</p></section>}
 <details className="provider-details" aria-label="Research connections"><summary>Research connections</summary><p><b>Local evidence</b><span>{health?.rag_ready?'Ready':'Checking connection'}</span></p><p><b>Tavily sources</b><span>{status('tavily')}</span></p>{finished&&researchStatus&&<small>{researchStatus.explanation_provider&&researchStatus.explanation_provider!=='calculated'?'Explanation supplied by '+researchStatus.explanation_provider+'. Later providers were not called.':researchStatus.gemini==='complete'?'Explanation returned by Gemini.':'Calculated explanation used; no AI provider returned usable text.'}</small>}{(['openrouter','groq','gemini'] as const).map(provider=><p key={provider}><b>{provider==='openrouter'?'OpenRouter · primary':provider==='groq'?'Groq · second choice':'Gemini · last fallback'}</b><span>{status(provider)}</span></p>)}<small>Python calculates the financial results independently of the optional APIs.</small>{onRetry&&!loading&&((!researchStatus?.explanation_provider||researchStatus.explanation_provider==='calculated')&&(retryableProvider(researchStatus?.gemini)||retryableProvider(researchStatus?.groq)||retryableProvider(researchStatus?.openrouter))||retryableProvider(researchStatus?.tavily))&&<><button type="button" className="text-link" onClick={onRetry}>Retry research with current inputs</button><small>This makes another request and can use your API quota.</small></>}</details><a className="text-link" href="/methodology">How the comparison works →</a></aside>;
}
