'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import dynamic from 'next/dynamic';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Leaf,Layers3,BookOpen,Globe2,Sparkles,Check,Plus,Minus,Sun} from 'lucide-react';
import {Button} from '@/components/ui/button';
import SiteHeader from '@/components/SiteHeader';
const WorldScene=dynamic(()=>import('@/components/WorldScene'),{ssr:false,loading:()=> <div className="world-fallback">Preparing your building…</div>});
export default function Home(){
 const router=useRouter();const [floors,setFloors]=useState(2),[solar,setSolar]=useState(true);const reduced=useReducedMotion(),reveal={initial:false as const};
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('project'))router.replace('/compare'+window.location.search);},[router]);
 return <div className="landing"><SiteHeader/>
 <a className="skip-link" href="/compare">Skip to calculator</a><main><section className="landing-hero"><motion.div className="hero-text" {...reveal}><div className="hero-tag"><span className="live-dot"/> A LONGER VIEW OF BETTER BUILDINGS</div><h1>Build better.<br/>Spend <em>smarter.</em><span className="hero-spark" aria-hidden="true">✳</span></h1><p>Good for your building.<br/>Better for your future.</p><p className="hero-description">Compare conventional and sustainable building costs with a research companion that turns your inputs into insight.</p><div className="hero-actions"><Button onClick={()=>router.push('/compare')}>Start comparison <ArrowUpRight size={17}/></Button><button className="sample-link" onClick={()=>router.push('/compare?sample=1')}>Explore a sample <ArrowRight size={16}/></button></div><div className="hero-trust"><span><Check size={13}/> Evidence you can follow</span><span><Check size={13}/> Assumptions you control</span></div></motion.div>
 <motion.div className="world-panel" initial={false} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.15}}><div className="world-top"><span><i/> YOUR FUTURE, IN FOCUS</span></div><div className="world-scene"><WorldScene floors={floors} solar={solar} busy={false}/></div><motion.div className="floating-note note-research" animate={reduced?{}:{y:[0,-8,0]}} transition={{duration:5,repeat:Infinity}}><span className="note-icon"><BookOpen size={16}/></span><div><b>Research meets reality</b><small>Reference rates + research</small></div></motion.div><motion.div className="floating-note note-future" animate={reduced?{}:{y:[0,7,0]}} transition={{duration:4,repeat:Infinity,delay:1}}><span className="note-icon amber"><Leaf size={16}/></span><div><b>Every year matters</b><small>30, 40 & 50-year comparisons</small></div></motion.div><div className="world-controls"><div><span>Floors</span><button aria-label="Remove floor" disabled={floors===1} onClick={()=>setFloors(Math.max(1,floors-1))}><Minus size={13}/></button><b>{floors}</b><button aria-label="Add floor" disabled={floors===4} onClick={()=>setFloors(Math.min(4,floors+1))}><Plus size={13}/></button></div><button className={solar?'solar-toggle active':'solar-toggle'} aria-pressed={solar} onClick={()=>setSolar(!solar)}><Sun size={15}/> Solar <span/></button><small>Drag to explore</small></div></motion.div></section>
 <div className="research-strip"><span>Thoughtful decisions.<br/><b>Grounded in real research.</b></span><div><BookOpen size={20}/><span>Included<br/><b>research library</b></span></div><div><Globe2 size={20}/><span>Official NSW<br/><b>source context</b></span></div><div><Sparkles size={20}/><span>Optional AI<br/><b>explanations</b></span></div><span className="strip-mark">✳</span></div>
 <section className="how-section" id="how-it-works"><motion.div className="section-intro" {...reveal}><span className="eyebrow">LESS GUESSWORK. MORE PERSPECTIVE.</span><h2>A few inputs.<br/>A whole new outlook.</h2><p>No spreadsheet gymnastics. Just your building, the evidence, and a clear comparison.</p></motion.div><div className="how-cards">{[{title:'Tell us about your building',text:'Start with your budget, utility bills and the upgrades you have in mind.',icon:Layers3},{title:'Let your companion research',text:'Review a cost breakdown, explore upgrades and compare long-term costs.',icon:Sparkles},{title:'See the bigger picture',text:'Explore costs, trade-offs and a clear explanation across the years ahead.',icon:Leaf}].map((card,i)=><motion.article key={card.title} {...reveal} transition={{duration:.5,delay:i*.1}}><div><card.icon size={21}/><span>0{i+1}</span></div><h3>{card.title}</h3><p>{card.text}</p></motion.article>)}</div></section>
 <section id="evidence" className="landing-evidence compact-evidence"><span className="eyebrow">CLEAR ASSUMPTIONS. TRACEABLE SOURCES.</span><h2>Know what’s behind the numbers.</h2><p>Review the Sydney reference rates, calculation method and research limitations.</p><a className="text-link" href="/methodology">Explore method & evidence <ArrowUpRight size={16}/></a></section>
 <section className="closing-note"><Leaf size={22}/><h2>Better buildings start<br/>with a longer view.</h2><Button onClick={()=>router.push('/compare')}>Take the first step <ArrowUpRight size={16}/></Button></section></main><footer className="landing-footer"><a href="/" className="footer-brand">greencost</a><a href="/methodology">Method &amp; evidence</a><span>Built for a thoughtful future.</span><small>Indicative planning tool · Costs in AUD</small></footer></div>;
}
