'use client';

import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Leaf,Layers3,BookOpen,Globe2,Sparkles,Check,Plus,Minus,Sun,ShieldCheck,X,ChevronDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import ProjectForm from '@/components/ProjectForm';
import ResearchAgent from '@/components/ResearchAgent';
import Results from '@/components/Results';
import Sources from '@/components/Sources';
import {downloadFile} from '@/lib/exports';
import {blankProject} from '@/lib/project';
import {api,streamAnalysis,type Project,type Analysis,type Health,type Source} from '@/lib/types';

const WorldScene=dynamic(()=>import('@/components/WorldScene'),{ssr:false,loading:()=> <div className="world-fallback">Preparing your building…</div>});
function jump(id:string){document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}

export default function Home(){
 const [project,setProject]=useState<Project>(blankProject),[analysis,setAnalysis]=useState<Analysis|null>(null);
 const [health,setHealth]=useState<Health|null>(null),[sources,setSources]=useState<Source[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [recent,setRecent]=useState<Analysis[]>([]),[deviceMessage,setDeviceMessage]=useState('');
 const [completed,setCompleted]=useState<string[]>([]),[message,setMessage]=useState(''),[uploading,setUploading]=useState(false),[uploadMessage,setUploadMessage]=useState('');
 const [floors,setFloors]=useState(2),[solar,setSolar]=useState(true);const reduced=useReducedMotion(),busy=useRef(false);
 const reveal={initial:reduced?false:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.6}};
 useEffect(()=>{
 try{const stored=JSON.parse(localStorage.getItem('greencost-recent-v1')??'[]');if(Array.isArray(stored))setRecent(stored.filter(r=>r?.id&&r?.project&&r?.periods).slice(0,3));}catch{setDeviceMessage('Browser history is unavailable. You can still download and share projects.');}
 const encoded=new URLSearchParams(window.location.search).get('project');
 if(encoded){try{if(encoded.length>24000)throw new Error('Shared project is too large.');const bytes=Uint8Array.from(atob(encoded.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const raw=JSON.parse(new TextDecoder().decode(bytes));api<Project>('/v1/validate',raw).then(p=>{setProject(p);setDeviceMessage('Shared inputs loaded with captured utility rates. Choose Analyse to reproduce the comparison.');jump('comparison');}).catch(e=>setError(e.message));}catch{setError('This shared link is invalid. Load a downloaded project or start fresh.');}}
 api<Health>('/health').then(setHealth).catch(()=>setError('The backend is not connected. Run scripts/start-local.ps1, then refresh this page.'));api<Source[]>('/sources').then(setSources).catch(()=>{});},[]);
 async function sample(){try{const demo=await api<Project>('/demo');setProject({...demo,web_research:true});setError('');}catch{setError('Connect the backend to load the sample project.');}}
 async function analyse(){if(busy.current)return;busy.current=true;setLoading(true);setError('');setCompleted([]);setMessage('Validating your project and preparing the research workflow…');try{const data=await streamAnalysis(project,event=>{if(event.type==='stage'&&event.stage){setCompleted(previous=>[...previous,event.stage!]);setMessage(event.message??'');}});setAnalysis(data);setRecent(previous=>{const updated=[data,...previous].slice(0,3);try{localStorage.setItem('greencost-recent-v1',JSON.stringify(updated));}catch{setDeviceMessage('Comparison complete. Device storage is full or disabled; download the project to keep it.');}return updated;});setMessage(data.research_status?.gemini==='complete'?'Your comparison and Gemini explanation are ready.':'Your comparison is ready. See the result for research connection details.');setTimeout(()=>jump('results'),100);}catch(e){setError((e as Error).message);setMessage('The analysis did not finish. Review the message and try again.');}finally{setLoading(false);busy.current=false;}}
 async function importProject(file:File){try{if(file.size>256*1024)throw new Error('Project file is too large.');const parsed=JSON.parse(await file.text());const raw=parsed.project??parsed;const checked=await api<Project>('/v1/validate',raw);setProject(checked);setDeviceMessage('Project inputs loaded. Choose Analyse to run the comparison.');}catch(e){setError((e as Error).message);}}
 async function upload(file:File){if(file.size>10*1024*1024){setUploadMessage('Choose a PDF smaller than 10 MB.');return;}setUploading(true);setUploadMessage('Reading pages and adding passages to your knowledge base…');try{const response=await fetch('/api/knowledge/pdf?filename='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/pdf'},body:file});const result=await response.json();if(!response.ok)throw new Error(result.detail??'This PDF could not be indexed.');setHealth(await api<Health>('/health'));setUploadMessage(`${file.name} added. ${result.chunks} passages are searchable in your library.`);}catch(e){setUploadMessage((e as Error).message);}finally{setUploading(false);}}
 return <div className="landing"><header className="landing-header"><a href="#" className="landing-brand" aria-label="GreenCost Sydney home"><span><Layers3 size={24}/></span><b>greencost<span>SYDNEY</span></b></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#comparison">Your comparison</a><a href="/methodology">Method & evidence</a></nav><a href="#comparison" className="header-cta">Let’s build better <ArrowUpRight size={15}/></a></header>
 <a className="skip-link" href="#comparison">Skip to calculator</a><main><section className="landing-hero"><motion.div className="hero-text" {...reveal}><div className="hero-tag"><span className="live-dot"/> A LONGER VIEW OF BETTER BUILDINGS</div><h1>Build better.<br/>Spend <em>smarter.</em><span className="hero-spark" aria-hidden="true">✳</span></h1><p>Good for your building.<br/>Better for your future.</p><p className="hero-description">Compare conventional and sustainable building costs with a research companion that turns your inputs into insight.</p><div className="hero-actions"><Button onClick={()=>jump('comparison')}>Find your greener path <ArrowUpRight size={17}/></Button><button className="sample-link" onClick={async()=>{await sample();jump('comparison');}}>Explore a sample <ArrowRight size={16}/></button></div><div className="hero-trust"><span><Check size={13}/> Evidence you can follow</span><span><Check size={13}/> Assumptions you control</span></div></motion.div>
 <motion.div className="world-panel" initial={reduced?false:{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.15}}><div className="world-top"><span><i/> YOUR FUTURE, IN FOCUS</span><span>SYDNEY / NSW</span></div><div className="world-scene"><WorldScene floors={floors} solar={solar} busy={loading}/></div><motion.div className="floating-note note-research" animate={reduced?{}:{y:[0,-8,0]}} transition={{duration:5,repeat:Infinity}}><span className="note-icon"><BookOpen size={16}/></span><div><b>Research meets reality</b><small>Your PDFs + official sources</small></div></motion.div><motion.div className="floating-note note-future" animate={reduced?{}:{y:[0,7,0]}} transition={{duration:4,repeat:Infinity,delay:1}}><span className="note-icon amber"><Leaf size={16}/></span><div><b>Every year matters</b><small>30, 40 & 50-year comparisons</small></div></motion.div><div className="world-controls"><div><span>Floors</span><button aria-label="Remove floor" onClick={()=>setFloors(Math.max(1,floors-1))}><Minus size={13}/></button><b>{floors}</b><button aria-label="Add floor" onClick={()=>setFloors(Math.min(4,floors+1))}><Plus size={13}/></button></div><button className={solar?'solar-toggle active':'solar-toggle'} aria-pressed={solar} onClick={()=>setSolar(!solar)}><Sun size={15}/> Solar <span/></button><small>Drag to explore</small></div></motion.div></section>
 <div className="research-strip"><span>Thoughtful decisions.<br/><b>Grounded in real research.</b></span><div><BookOpen size={20}/><span>Your PDF<br/><b>knowledge base</b></span></div><div><Globe2 size={20}/><span>Official NSW<br/><b>source context</b></span></div><div><Sparkles size={20}/><span>Gemini-powered<br/><b>explanations</b></span></div><span className="strip-mark">✳</span></div>
 <section className="how-section" id="how-it-works"><motion.div className="section-intro" {...reveal}><span className="eyebrow">LESS GUESSWORK. MORE PERSPECTIVE.</span><h2>A few inputs.<br/>A whole new outlook.</h2><p>No spreadsheet gymnastics. Just your building, the evidence, and a clear comparison.</p></motion.div><div className="how-cards">{[{title:'Tell us about your building',text:'Start with your budget, utility bills and the upgrades you have in mind.',icon:Layers3},{title:'Let your companion research',text:'Relevant PDF passages meet official web context to inform your comparison.',icon:Sparkles},{title:'See the bigger picture',text:'Explore costs, trade-offs and a clear explanation across the years ahead.',icon:Leaf}].map((card,i)=><motion.article key={card.title} {...reveal} transition={{duration:.5,delay:i*.1}}><div><card.icon size={21}/><span>0{i+1}</span></div><h3>{card.title}</h3><p>{card.text}</p></motion.article>)}</div></section>
 <section id="comparison" className="comparison-section"><motion.div className="comparison-intro" {...reveal}><div><span className="eyebrow">MAKE IT YOURS</span><h2>Your building.<br/><em>Your better tomorrow.</em></h2></div><p>Start simple. Refine as you go.<br/>We’ll help you see what makes a difference.</p></motion.div>
 {error&&<div className="comparison-error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 <div className="device-tools"><label className="upload-button">Open saved project<input type="file" accept="application/json,.json" disabled={loading} onChange={e=>{const file=e.target.files?.[0];if(file)void importProject(file);e.target.value='';}}/></label><button disabled={loading} onClick={async()=>{try{setProject(await api<Project>('/demo?legacy=true'));setDeviceMessage('Legacy fixture loaded. This older study example is not a code-minimum new home.');}catch(e){setError((e as Error).message);}}}>Load legacy study example</button><button onClick={()=>downloadFile(JSON.stringify({project},null,2),'GreenCost-inputs.json')}>Save current inputs</button></div>{deviceMessage&&<p className="small-note" role="status">{deviceMessage}</p>}{recent.length>0&&<details className="recent-projects"><summary>Recent comparisons on this device ({recent.length})</summary>{recent.map(r=><button key={r.id} disabled={loading} onClick={()=>{setProject(r.project);setAnalysis(r);setTimeout(()=>jump('results'),50);}}>{r.project.name} · {r.project.years} years</button>)}<button onClick={()=>{setRecent([]);try{localStorage.removeItem('greencost-recent-v1');}catch{}}}>Clear device history</button></details>}<div className="comparison-grid"><ProjectForm project={project} onChange={setProject} onAnalyse={analyse} loading={loading||uploading} onDemo={sample} onReset={()=>{setProject(blankProject());setError('');}}/><ResearchAgent health={health} loading={loading} completed={completed} message={message} failed={!!error} finished={!!analysis&&!loading} webEnabled={project.web_research} onUpload={upload} uploading={uploading} uploadMessage={uploadMessage}/></div>
 <p className="comparison-footnote"><ShieldCheck size={14}/> Your financial results are calculated consistently. AI helps explain the evidence and trade-offs.</p></section>
 <div id="results" className="inline-results" aria-live="polite">{analysis?<Results key={analysis.id} data={analysis} onEdit={()=>jump('comparison')}/>:<motion.section className="result-placeholder" {...reveal}><div><span className="placeholder-icon"><Leaf size={25}/></span><span className="eyebrow">A CLEARER PICTURE AWAITS</span><h2>See beyond the upfront price.</h2><p>Your life-cycle comparison, cost charts and research-backed explanation will appear here.</p></div><div className="placeholder-items"><span><Check size={15}/> Full life-cycle costs</span><span><Check size={15}/> Break-even & sensitivity</span><span><Check size={15}/> Sources & clear explanations</span></div></motion.section>}</div>
 <section id="evidence" className="landing-evidence"><motion.div className="evidence-heading" {...reveal}><span className="eyebrow">A PAPER TRAIL, NOT A BLACK BOX</span><h2>Good decisions have<br/><em>good foundations.</em></h2><p>Official tariff references inform costs. Research PDFs and web context support interpretation. You can inspect the assumptions behind every result.</p></motion.div><Sources sources={sources}/><details className="landing-methodology"><summary>How the comparison works <ChevronDown size={17}/></summary><p>Both scenarios use the same building geometry. Capital occurs at year zero. Annual energy, water, maintenance, replacement and other costs are escalated and discounted to present value. Disposal and residual value occur at each study endpoint. Itemised upgrades use indicative end-use interactions; literature mode uses entered package reductions. No star rating or regulatory compliance is inferred.</p><p>Every analysis includes 30-, 40- and 50-year horizons and 48 sensitivity combinations. It is an indicative scenario comparison, not a construction quotation or a building-performance certification.</p></details><details className="landing-methodology setup"><summary>Research connections <ChevronDown size={17}/></summary><p>Gemini: {health?.gemini_configured?'connected':'not configured'} · Tavily: {health?.tavily_configured?'connected':'not configured'} · Local library: {health?.rag_ready?'knowledge base ready':'not indexed'}</p><p>For AI explanations and web research, copy .env.example to .env in the project folder, add GEMINI_API_KEY and TAVILY_API_KEY, then restart the backend. Keys stay on the server. Without keys, the calculator and local PDF evidence remain available.</p><p>Relevant PDF excerpts and non-identifying scenario facts are sent to Gemini when connected. Tavily receives a general building-and-feature search. Turn off web research in the form to skip Tavily.</p></details></section>
 <section className="closing-note"><Leaf size={22}/><h2>Better buildings start<br/>with a longer view.</h2><Button onClick={()=>jump('comparison')}>Take the first step <ArrowUpRight size={16}/></Button></section></main>
 <footer className="landing-footer"><a href="#" className="footer-brand">greencost <span>SYDNEY</span></a><a href="/methodology">Method &amp; evidence</a><span>Built for a thoughtful future.</span><small>Indicative planning tool · Costs in AUD</small></footer></div>;
}
