'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {FolderOpen,RefreshCw,ShieldCheck,X,Upload,ArrowRight} from 'lucide-react';
import SiteHeader from '@/components/SiteHeader';
import GuidedForm from '@/components/GuidedForm';
import ResearchAgent from '@/components/ResearchAgent';
import Results from '@/components/Results';
import Toast,{type Notice} from '@/components/Toast';
import {draftKey,restoreDraft,defaultPosition,type FormPosition} from '@/lib/client-planning';
import {blankProject} from '@/lib/project';
import {api,streamAnalysis,ApiError,type Project,type Analysis,type Health} from '@/lib/types';
function jump(id:string){document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
export default function Compare(){
 const [project,setProject]=useState<Project>(blankProject),[analysis,setAnalysis]=useState<Analysis|null>(null);
 const [health,setHealth]=useState<Health|null>(null),[connection,setConnection]=useState<'checking'|'ready'|'offline'>('checking');
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[serverFields,setServerFields]=useState<Record<string,string>>({}),[formVersion,setFormVersion]=useState(0);
 const [recent,setRecent]=useState<Analysis[]>([]),[projectsOpen,setProjectsOpen]=useState(false),[notice,setNotice]=useState<Notice|null>(null);
 const [completed,setCompleted]=useState<string[]>([]),[message,setMessage]=useState('');
 const [position,setPosition]=useState<FormPosition>(defaultPosition),[draftReady,setDraftReady]=useState(false),[draftSaved,setDraftSaved]=useState(false),[resetOpen,setResetOpen]=useState(false);
 const [activeStage,setActiveStage]=useState(''),[liveProviders,setLiveProviders]=useState<{gemini?:string;groq?:string;openrouter?:string;tavily?:string}>({});
 const projectRef=useRef(project),positionRef=useRef(position);projectRef.current=project;positionRef.current=position;
 const busy=useRef(false),fileInput=useRef<HTMLInputElement>(null);
 const notify=useCallback((message:string)=>setNotice({message,id:Date.now()}),[]),dismiss=useCallback(()=>setNotice(null),[]);
 const reconnect=useCallback(async()=>{setConnection('checking');try{setHealth(await api<Health>('/health'));setConnection('ready');}catch{setHealth(null);setConnection('offline');}},[]);
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void reconnect();};window.addEventListener('online',refresh);window.addEventListener('focus',refresh);return()=>{window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh);};},[reconnect]);
 function replaceProject(p:Project){window.history.replaceState(window.history.state,'',window.location.pathname);setPosition(defaultPosition);setProject({...blankProject(),...p});setAnalysis(null);setMessage('');setCompleted([]);setActiveStage('');setLiveProviders({});setServerFields({});setError('');setFormVersion(v=>v+1);}
 async function sample(){try{replaceProject(await api<Project>('/demo'));notify('Example loaded. Replace its assumptions with your project details.');}catch{setError('The example could not load. Check the connection and try again.');}}
 useEffect(()=>{
  void reconnect();
  try{const stored=JSON.parse(localStorage.getItem('greencost-recent-v1')??'[]');if(Array.isArray(stored))setRecent(stored.filter(r=>typeof r?.id==='string'&&typeof r?.project?.name==='string'&&r?.periods).slice(0,3));}catch{notify('Device history is unavailable. You can still save project files.');}
  const params=new URLSearchParams(window.location.search),encoded=params.get('project');
  if(encoded){try{if(encoded.length>24000)throw new Error();const bytes=Uint8Array.from(atob(encoded.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const raw=JSON.parse(new TextDecoder().decode(bytes));api<Project>('/v1/validate',raw).then(p=>{replaceProject(p);notify('Shared inputs loaded. Review them before comparing.');}).catch(()=>setError('The shared project could not load. Retry once the connection is ready.'));}catch{setError('This share link is invalid. Import a saved project or start fresh.');}}
  else if(params.get('sample')==='1')void sample();
  else {try{const draft=restoreDraft(localStorage.getItem(draftKey));if(draft){setProject({...blankProject(),...draft.project});setPosition(draft.position);notify('Your draft is restored. Continue where you left off.');}}catch{notify('Browser draft storage is unavailable. Use Save draft to keep a file.');}}
  setDraftReady(true);
 // Run URL import once; editing must not reapply initial inputs.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[reconnect,notify]);
 useEffect(()=>{if(!draftReady)return;const save=()=>{try{localStorage.setItem(draftKey,JSON.stringify({version:3,project:projectRef.current,position:positionRef.current,savedAt:new Date().toISOString()}));setDraftSaved(true);}catch{setDraftSaved(false);}};save();window.addEventListener('pagehide',save);return()=>window.removeEventListener('pagehide',save);},[project,position,draftReady]);
 async function analyse(input:Project=project){if(busy.current)return;busy.current=true;setLoading(true);setError('');setServerFields({});setCompleted([]);setActiveStage('validate_input');setLiveProviders({});setMessage('Checking your project and preparing the comparison…');try{
  const data=await streamAnalysis({...input,name:input.name.trim()||'My project'},event=>{if(event.type==='stage_start'&&event.stage)setActiveStage(event.stage);if(event.type==='stage'&&event.stage){setCompleted(previous=>previous.includes(event.stage!)?previous:[...previous,event.stage!]);setMessage(event.message??'');if(event.providers)setLiveProviders(previous=>({...previous,...event.providers}));}});
  setAnalysis(data);setRecent(previous=>{const updated=[data,...previous.filter(r=>r.id!==data.id)].slice(0,3);try{localStorage.setItem('greencost-recent-v1',JSON.stringify(updated));}catch{notify('Device storage is unavailable. Save your project file to keep it.');}return updated;});setMessage('Your comparison is ready.');notify('Comparison ready.');setTimeout(()=>jump('results'),100);
 }catch(e){if(e instanceof ApiError&&Object.keys(e.fields).length){setServerFields(e.fields);setMessage('Review the highlighted fields.');}else{setError(e instanceof TypeError||e instanceof DOMException?'The connection was interrupted. Your inputs are preserved; retry when the calculator is connected.':(e as Error).message);setMessage('The comparison did not finish. Your inputs are still here.');void reconnect();}}finally{setLoading(false);busy.current=false;}}
 async function importProject(file:File){try{if(file.size>256*1024)throw new Error('Choose a GreenCost JSON file smaller than 256 KB.');const parsed=JSON.parse(await file.text()),raw=parsed.project??parsed,draft=parsed.kind==='greencost-draft-v2';const checked=await api<Project>(draft?'/v1/draft':'/v1/validate',raw);replaceProject(checked);setProjectsOpen(false);notify(draft?'Draft restored. Complete the remaining fields.':'Project imported. Review your inputs and compare.');}catch(e){setError(e instanceof SyntaxError?'Choose a valid GreenCost JSON project file.':(e as Error).message);}}
 async function openRecent(r:Analysis){try{replaceProject(await api<Project>('/v1/validate',r.project));setProjectsOpen(false);notify('Saved inputs restored. Compare again for a new result.');}catch(e){setError((e as Error).message);}}
 return <div className="landing compare-page"><SiteHeader compare/><a className="skip-link" href="#comparison">Skip to calculator</a><main>
 <section id="comparison" className="comparison-section"><div className="comparison-intro"><div><span className="eyebrow">YOUR PROJECT</span><h1>One building.<br/><em>Two possibilities.</em></h1><p>Tell us what you know. Review the estimates. Compare the years ahead.</p></div><button className="projects-trigger" onClick={()=>setProjectsOpen(v=>!v)} aria-expanded={projectsOpen} aria-controls="my-projects"><FolderOpen size={18}/>My projects</button></div>
 {projectsOpen&&<section id="my-projects" className="projects-panel" aria-label="My projects"><div className="section-heading"><div><h2>Pick up where you left off</h2><p>Import a GreenCost JSON file, or resume inputs saved in this browser.</p></div><button onClick={()=>setProjectsOpen(false)} aria-label="Close My projects"><X size={18}/></button></div><button type="button" className="import-project" disabled={loading} onClick={()=>fileInput.current?.click()}><Upload size={17}/>Import saved project</button><input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importProject(file);e.target.value='';}}/><h3>Saved on this device</h3>{recent.length?recent.map(r=><button key={r.id} className="saved-project" disabled={loading} onClick={()=>void openRecent(r)}><span><b>{r.project.name}</b><small>{r.project.postcode} · {r.project.years}-year study · {r.project.price_date}</small></span><ArrowRight size={17}/></button>):<p className="small-note">Your last three completed comparisons appear here. They stay in this browser.</p>}{recent.length>0&&<button className="text-link" onClick={()=>{setRecent([]);try{localStorage.removeItem('greencost-recent-v1');notify('Device history cleared. Downloaded files are unchanged.');}catch{setError('Device history could not be cleared. Check browser storage permissions.');}}}>Clear device history</button>}</section>}
 <div className={'connection-status '+connection} role="status"><span className="status-dot"/><span>{connection==='ready'?'Calculator connected':connection==='checking'?'Connecting to the calculator…':'Calculator connection unavailable. Your inputs are safe.'}</span>{connection==='offline'&&<><button onClick={()=>void reconnect()}><RefreshCw size={14}/>Retry connection</button><details><summary>Connection help</summary><p>For local testing, keep GreenCost’s server terminal running. If it stopped, run <code>.\scripts\start-local.ps1 -Production</code> from the project folder, then retry. The browser alone does not run the calculator.</p></details></>}</div>
 {error&&<div className="action-error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss action error"><X size={16}/></button></div>}
 <div className="draft-status" role="status">{draftSaved?'Draft saved automatically in this browser':'Complete your project at your own pace. Save a draft file if browser storage is unavailable.'}</div>{resetOpen&&<div id="reset-values" className="reset-confirm" role="alert" tabIndex={-1}><b>Reset all values and start again?</b><p>This clears your current inputs and results, then returns to Building details. Saved comparisons in My projects remain available.</p><button type="button" onClick={()=>setResetOpen(false)}>Keep my draft</button><button type="button" onClick={()=>{replaceProject(blankProject());setResetOpen(false);setProjectsOpen(false);notify('Values reset. Start your new calculation from Building details.');requestAnimationFrame(()=>jump('comparison'));}}>Reset and start again</button></div>}
 {draftReady&&<div className="comparison-grid"><GuidedForm key={formVersion} position={position} onPositionChange={setPosition} project={project} onChange={p=>{setProject(p);setServerFields({});}} onAnalyse={analyse} loading={loading} onDemo={sample} onReset={()=>{setResetOpen(true);requestAnimationFrame(()=>{jump('reset-values');document.getElementById('reset-values')?.focus({preventScroll:true});});}} onNotify={notify} serverErrors={serverFields} connected={connection==='ready'}/><ResearchAgent activeStage={activeStage} liveProviders={liveProviders} health={health} loading={loading} completed={completed} message={message} failed={!!error} finished={!!analysis&&!loading} webEnabled={project.web_research} researchStatus={analysis?.research_status} onRetry={()=>void analyse()}/></div>}<p className="comparison-footnote"><ShieldCheck size={14}/>Calculated costs, transparent assumptions and optional research explanations.</p></section>
 <div id="results" className="inline-results">{analysis?<Results key={analysis.id} data={analysis} onEdit={()=>jump('comparison')} onNotify={notify} onRetryResearch={()=>void analyse(analysis.project)}/>:<section className="result-placeholder"><h2>Your comparison will appear here.</h2><p>Complete the three steps to see upfront differences, whole-life costs and break-even.</p></section>}</div>
 </main><footer className="landing-footer"><a href="/">greencost</a><a href="/methodology">Method & evidence</a><small>Indicative planning tool · Costs in AUD</small></footer><Toast notice={notice} onDismiss={dismiss}/></div>;
}
