'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import Sources from '@/components/Sources';
import {api,type Source} from '@/lib/types';
export default function Methodology(){
 const [sources,setSources]=useState<Source[]>([]),[assumptions,setAssumptions]=useState<Record<string,unknown>|null>(null),[error,setError]=useState('');
 useEffect(()=>{api<Source[]>('/sources').then(setSources).catch(()=>setError('Connect the backend to inspect the dated source register.'));api<Record<string,unknown>>('/v1/assumptions').then(setAssumptions).catch(()=>{});},[]);
 return <main className="method-page"><nav className="method-nav" aria-label="Main navigation"><Link href="/">greencost / SYDNEY</Link><Link href="/#comparison">Back to your comparison →</Link></nav><p className="eyebrow">TRANSPARENT BY DESIGN</p><h1>A comparison you can inspect.</h1><p>GreenCost compares the same house with two specifications over 30, 40 and 50 years. It shows what follows from your inputs, under the stated assumptions. It does not predict the performance of a completed home.</p>
 <h2>How costs are calculated</h2><pre>LCC = initial construction + discounted annual costs + discounted disposal − discounted salvage</pre><p>Initial costs occur in year zero. Base-year utility prices, maintenance and replacement costs grow at your chosen annual rates and are discounted back to today. Replacements occur at the entered intervals before retirement. Disposal and salvage occur at each study endpoint. All values are nominal Australian dollars.</p><p>A discount rate gives less weight to costs further in the future. Break-even is the first year when the sustainable home’s cumulative discounted cost becomes no higher than the conventional home’s. It can reverse later, for example after a replacement. Equivalent annual cost spreads present-value cost across the horizon using the same discount rate.</p>
 <h2>Two ways to explore</h2><p><b>Itemised mode</b> adds the installed cost difference of each selected upgrade. Geometry estimates quantities for a rectangular house. The energy model applies envelope and appliance changes to specific end uses, then calculates solar self-use and exports. Combined effects are applied together, so overlapping savings are not added twice. Marginal contributions add upgrades in catalogue order; the interaction adjustment reconciles standalone and combined effects.</p><p><b>Literature mode</b> applies your package premium and operating reductions. It also calculates low, mid and high literature-parameter scenarios. Usage reductions affect variable utility charges; fixed supply and water service charges remain. Research ranges are assumptions, not a promise of 10–20% whole-life savings.</p><p><b>Legacy preset</b> preserves the package’s older study example and original year-one escalation convention. It uses one-off replacement events. It is a regression fixture, not a compliant new-house specification. Current scenarios use the existing app’s base-year escalation convention. These differences are deliberate and tested.</p>
 <h2>What is sourced, and what is indicative?</h2><p>Current utility references have organisation, effective period and source links. Upgrade premiums, end-use splits, geometry, installation quality, solar yield, maintenance and service lives are indicative unless replaced by project evidence. Code-minimum is a provisional baseline: the required design depends on the building, location and approval pathway. Selecting measures does not establish a NatHERS rating or BASIX compliance.</p><p>The house takeoff assumes a 1.5 plan aspect ratio, 2.7 metre storey height, glazing equal to 18% of floor area, and a roof factor of 1.15. These supplied assumptions are placeholders. Use drawing quantities where available. Solar capacity is checked against an indicative roof area; rainwater savings are limited by catchment, storage and non-potable demand.</p>
 <details><summary>Energy-model boundaries</summary><p>Baseline electricity is split into heating/cooling, hot water, lighting and appliances using indicative proportions. Insulation, glazing and sealing multiply heating demand reductions; HVAC efficiency acts on that remaining demand. Gas is allocated to space heating. The model does not claim fuel-switch savings. If the baseline already has efficient LED lighting, selecting lighting has no modelled electricity reduction. Solar self-use is capped by remaining load; exports earn the entered tariff. Batteries and time-of-use schedules are outside this model.</p></details>
 <details><summary>Pricing and incentives</summary><p>Supplied upgrade prices are installed differences, with labour, margin and GST already included. They are labelled Indicative. A user quote overrides the default. Mark a measure already included in your baseline to set its incremental cost and benefit to zero. The illustrative low/high ranges are ±20% around defaults; they are uncertainty assumptions, not live offers. Incentive eligibility and amounts require a dated installer quote; no rebate is applied automatically.</p><p><a href="https://cer.gov.au/schemes/renewable-energy-target/small-scale-renewable-energy-scheme">Federal Small-scale Renewable Energy Scheme</a> and <a href="https://www.energy.nsw.gov.au/households/rebates-grants-and-schemes/household-energy-saving-upgrades/upgrade-your-hot-water">NSW hot-water upgrades</a> have eligibility conditions. Check current requirements with the installer.</p></details>
 <details><summary>All region assumptions and catalogue data</summary>{assumptions?<pre>{JSON.stringify(assumptions,null,2)}</pre>:<p>Connect the backend to load the assumptions register.</p>}</details>
 <h2>Evidence register</h2>{error&&<p role="status">{error}</p>}<Sources sources={sources}/>
 <h2>Privacy</h2><p>No accounts or databases are used. Recent comparisons stay in this browser and can be cleared. Downloaded files and share links contain project inputs; share them only with people you choose. Local installations can save JSON analysis files and uploaded research PDFs. Vercel deployments use a read-only research library and keep no durable server history.</p><p>With optional AI enabled, Gemini receives non-identifying scenario facts and selected research excerpts. Tavily receives a general building-feature search. Keys stay on the backend. Free-tier providers may use submitted data under their own terms. Avoid confidential research or personal information. Turning off web research skips Tavily; hosted AI is disabled by default.</p>
 <h2>Use and limitations</h2><p>This is an indicative planning and research tool, not a construction quotation, financial recommendation, or NatHERS/BASIX assessment. Verify assumptions with your builder, quantity surveyor and energy assessor before making a building decision. Site conditions, excavation, bushfire/flood requirements, orientation, shading, network approvals and installation quality need project-specific assessment. Past snapshots contain dated tariffs; recheck prices before relying on a shared example.</p><p>The project owner must approve public-launch wording and verify provisional inputs before presenting the model as authoritative. Vercel Hobby is for personal, non-commercial use. Commercial deployment needs a suitable hosting plan.</p><p><Link href="/#comparison">Create your comparison →</Link></p></main>;
}
